#pragma once
String config_html = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<title>Microcontroller Parameter Setting</title>\n"
"</head>\n"
"<body>\n"
"<div>\n"
"<label>Run:</label>\n"
"<input type=\"number\" id=\"runInput\" min=\"0\" max=\"100\" value=\"{{RUN_VALUE}}\">\n"
"<button onclick=\"sendParam('run')\">Set</button>\n"
"</div>\n"
"<div>\n"
"<label>Turn:</label>\n"
"<input type=\"number\" id=\"turnInput\" min=\"0\" max=\"100\" value=\"{{TURN_VALUE}}\">\n"
"<button onclick=\"sendParam('turn')\">Set</button>\n"
"</div>\n"
"<div>\n"
"<label>Spin:</label>\n"
"<input type=\"number\" id=\"spinInput\" min=\"0\" max=\"100\" value=\"{{SPIN_VALUE}}\">\n"
"<button onclick=\"sendParam('spin')\">Set</button>\n"
"</div>\n"
"\n"
"<script>\n"
"function sendParam(paramName) {\n"
"const input = document.getElementById(paramName + 'Input');\n"
"const value = parseInt(input.value);\n"
"\n"
"const url = `http://{{CURRENT_IPADDR}}/api?ev=config&name=${paramName}&val=${value}`;\n"
"\n"
"fetch(url, {\n"
"method: 'POST'\n"
"})\n"
".then(response => response.text())\n"
".then(data => {\n"
"alert(data);\n"
"})\n"
".catch(error => {\n"
"alert('Error: ' + error.message);\n"
"});\n"
"}\n"
"</script>\n"
"</body>\n"
"</html>\n";