#pragma once
String index_html = 
"<!DOCTYPE html>\n"
"<html lang='en'>\n"
"<head>\n"
"<meta charset='utf-8'>\n"
"<title>PANJAN-D</title>\n"
"<style>\n"
"    html {font-family: Helvetica; display: inline-block; margin: 0px auto; text-align: center;}\n"
"    .noselect {user-select: none;}\n"
"    .button {display: inline-block; background-color: #0000FF; border: none; border-radius: 4px; padding: 16px 16px; text-decoration: none; font-size: 50px; margin: 2px; cursor: pointer;}\n"
"</style>\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"</head>\n"
"<body>\n"
"<center><h1>PANJAN-D</h1></center>\n"
" <div class='noselect'>\n"
" <center><table>\n"
"  <tr>\n"
"   <td> </td>\n"
"   <td> <center><button type='button' class='button'\n"
"            onmousedown=\"ControlButton('forward');\"\n"
"            ontouchstart=\"ControlButton('forward');\"\n"
"            onmouseup=\"ControlButton('stop');\"\n"
"            ontouchend=\"ControlButton('stop');\">\n"
"            &#x23eb;</button></center></td>\n"
"   <td> </td>\n"
"  </tr>\n"
"  <tr>\n"
"   <td> <center><button type='button' class='button'\n"
"            onmousedown=\"ControlButton('left');\"\n"
"            ontouchstart=\"ControlButton('left');\"\n"
"            onmouseup=\"ControlButton('stop');\"\n"
"            ontouchend=\"ControlButton('stop');\">\n"
"            &#x23ea;</button></center></td>\n"
"   <td> <center><button type='button' class='button'\n"
"            onmousedown=\"ControlButton('stop');\"\n"
"            ontouchstart=\"ControlButton('stop');\"\n"
"            onmouseup=\"ControlButton('stop');\"\n"
"            ontouchend=\"ControlButton('stop');\">\n"
"            &#x23f9;</button></center></td>\n"
"   <td> <center><button type='button' class='button'\n"
"            onmousedown=\"ControlButton('right');\"\n"
"            ontouchstart=\"ControlButton('right');\"\n"
"            onmouseup=\"ControlButton('stop');\"\n"
"            ontouchend=\"ControlButton('stop');\">\n"
"            &#x23e9;</button></center></td>\n"
"  </tr>\n"
"  <tr>\n"
"   <td> </td>\n"
"   <td> <center><button type='button' class='button'\n"
"            onmousedown=\"ControlButton('backward');\"\n"
"            ontouchstart=\"ControlButton('backward');\"\n"
"            onmouseup=\"ControlButton('stop');\"\n"
"            ontouchend=\"ControlButton('stop');\">\n"
"            &#x23ec;</button></center></td>\n"
"   <td> </td>\n"
"  </tr>\n"
"</table></center>\n"
"</div>\n"
"</body>\n"
"<script language='javascript' type='text/javascript'>\n"
" function ControlButton(value) {\n"
"  var request = new XMLHttpRequest();\n"
"  request.open('POST', 'http://{{CURRENT_IPADDR}}/api?ev=' + value, true);\n"
"  request.responseType = 'text';\n"
"  request.onload = function () {\n"
"   //do nothing\n"
"  };\n"
"  request.onerror = function () {\n"
"    alert('ERROR: Communication error.')\n"
"  };\n"
"  request.send();\n"
"}\n"
"</script>\n";